= Dashboard

Una delle principali pagine di Jeedom si visualizza un riepilogo di tutte vostro domotico. Questo rapporto (in contrasto con il punto di vista e il design) è auto-generato da Jeedom.

Si accede facendo clic su Casa -> Dashboard

immagine::../images/dashboard2.JPG[]

[TIP]
Come si può vedere nello screenshot è possibile accedere direttamente a un elemento nella domotico. Questo non avrà l'equipaggiamento che vi interessa e quindi caricare la pagina più velocemente

Ecco un dashboard campione

immagine::../images/dashboard.JPG[]

Hai alto a sinistra un piccolo simbolo per mostrare / nascondere l'albero degli oggetti: 

immagine::../images/dashboard1.JPG[]

Nel mezzo è possibile scegliere di filtrare solo su alcuni tipi di apparecchiature:

immagine::../images/dashboard3.JPG[]

A destra primo tasto per entrare in edit mode, ad esempio cambiando l'ordine dei widget (con un clic sul widget depositato), puoi anche in questo modo edizione ridimensionare alcuni widget e riorganizzare l'ordine comandi al loro interno

Poi tasto per visualizzare / nascondere gli scenari:

immagine::../images/dashboard4.JPG[]

[TIP]
E 'possibile dai vostri profili di configurare Jeedom per l'albero di oggetti e / o scenari è visibile di default quando si arriva sul Dashboard